# ============================================================================
# Streamlit Cloud Configuration για MedIllustrator-AI v3.0
# ============================================================================

[global]
# Development mode - set to false for production
developmentMode = false

# Share button - enable for easy sharing
showWarningOnDirectExecution = false

[server]
# Server settings optimized for cloud deployment
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50  # MB - increased for medical images
enableWebsocketCompression = true

# Port configuration (handled by Streamlit Cloud)
port = 8501

[browser]
# Browser settings for cloud deployment
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
# Client settings for better performance
caching = true
displayEnabled = true

[runner]
# Runner settings for stability
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true

[logger]
# Logging configuration
level = "INFO"
enableRich = false

[theme]
# Custom theme for medical application
primaryColor = "#FF6B6B"          # Medical red
backgroundColor = "#FFFFFF"        # Clean white
secondaryBackgroundColor = "#F0F2F6"  # Light gray
textColor = "#262730"             # Dark text

# Optional: Dark theme
# primaryColor = "#FF6B6B"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#FAFAFA"

[deprecation]
# Handle deprecation warnings
showPyplotGlobalUse = false
showfileUploaderEncoding = false